### ISSUE TITLE
NullPointerException: Cannot invoke "me.kodysimpson.simpapi.command.SubCommand.getName()" because the return value of "java.util.ArrayList.get(int)" is null

### ISSUE THREAD

**Issue by phntmcc** [Cortex-MC/SimpAPI#10]
I am getting a NullPointerException when I create an instance inside of a SubCommand class that passes through an instance of a JavaPlugin class.

```
   private Main plugin;

    public test(Main plugin) {
        this.plugin = plugin;
    }
```

If there is any way of solving this issue or a workaround would be greatly appreciated. Enjoying using the API but need functionality from the JavaPlugin class for certain commands

**Comment by frosxt** [comment]
You can work around this by using JavaPlugin#getPlugin like so:
`private final Main plugin = Main.getPlugin(Main.class);`

**Comment by KodySimpson** [comment]
Yeah I recommend doing a static accessor as a workaround for now
