### ISSUE TITLE
Autocomplete for subcommand

### ISSUE THREAD

**Issue by dwesolowski** [Cortex-MC/SimpAPI#26]
My subcommand will also have a argument, how would I implement autocomplete for it?

/root subcommand args

**Comment by KodySimpson** [comment]
Same way you normally would, except with the getcommandargs method

**Comment by dwesolowski** [comment]
So are you saying in the subcommand then use like the below in the getcommandargs method

```
if (args[3]) {
  Arrays.asList("one", "two")
}
```

**Comment by KodySimpson** [comment]
yep looks good

**Comment by KodySimpson** [comment]
close da issue bruh

**Comment by dwesolowski** [comment]
When testing for what should be args.length = 2, it displays the args at length 4

![Snag_3f53cea](https://user-images.githubusercontent.com/26182263/130345426-763dffed-d229-42d6-9e71-40f13b3c6f44.png)
